### ISSUE TITLE
Enhancement: Shorter duelstats output format

### ISSUE THREAD

**Issue by zephyrtronium** [firynth/DiscordBot-Issues#2]
`>duelstats` tends to be used by several people in clusters. Because its output is six lines long, this means it tends to fill up chat. Instead of the current format:

```
Wins: 5
Losses: 4
Ties: 0
Highest Win Streak: 3
Highest Loss Streak: 1
Current Win Streak: 2
```

I propose a shorter, one-line format:

```
5-4-0. Current streak: 2W. Best win streak: 3. Worst loss streak: 1.
```

**Comment by firynth** [comment]
It's two lines, but good enough
